GET http://localhost:3500/movies HTTP/1.1

###

GET http://localhost:3500/movies?title=The Flash 2 HTTP/1.1

###

GET http://localhost:3500/movies?title_like=Missão HTTP/1.1

###

POST http://localhost:3500/movies HTTP/1.1
Content-Type: application/json

{
    "title": "Missão Impossível - Protocolo Fantasma",
    "watched": true
}

###

PATCH http://localhost:3500/movies/3 HTTP/1.1
Content-Type: application/json

{
    "watched": false
}

###

PUT http://localhost:3500/movies/3 HTTP/1.1
Content-Type: application/json

{
    "title": "The Flash 2"
}

###

DELETE http://localhost:3500/movies/4 HTTP/1.1